var group__oscmethods =
[
    [ "SDTOSC", "group__oscroot.html", "group__oscroot" ],
    [ "SDTOSCBouncing", "group__oscbouncing.html", "group__oscbouncing" ],
    [ "SDTOSCBreaking", "group__oscbreaking.html", "group__oscbreaking" ],
    [ "SDTOSCBubble", "group__oscbubble.html", "group__oscbubble" ],
    [ "SDTOSCCrumpling", "group__osccrumpling.html", "group__osccrumpling" ],
    [ "SDTOSCDCMotor", "group__oscdcmotor.html", "group__oscdcmotor" ],
    [ "SDTOSCDemix", "group__oscdemix.html", "group__oscdemix" ],
    [ "SDTOSCEnvelope", "group__oscenvelope.html", "group__oscenvelope" ],
    [ "SDTOSCExplosion", "group__oscexplosion.html", "group__oscexplosion" ],
    [ "SDTOSCFluidFlow", "group__oscfluidflow.html", "group__oscfluidflow" ],
    [ "SDTOSCFriction", "group__oscfriction.html", "group__oscfriction" ],
    [ "SDTOSCImpact", "group__oscimpact.html", "group__oscimpact" ],
    [ "SDTOSCMotor", "group__oscmotor.html", "group__oscmotor" ],
    [ "SDTOSCMyoelastic", "group__oscmyo.html", "group__oscmyo" ],
    [ "SDTOSCPitch", "group__oscpitch.html", "group__oscpitch" ],
    [ "SDTOSCPitchShift", "group__oscpitchshift.html", "group__oscpitchshift" ],
    [ "SDTOSCProjects", "group__oscprojects.html", "group__oscprojects" ],
    [ "SDTOSCResonators", "group__oscresonators.html", "group__oscresonators" ],
    [ "SDTOSCReverb", "group__oscreverb.html", "group__oscreverb" ],
    [ "SDTOSCRolling", "group__oscrolling.html", "group__oscrolling" ],
    [ "SDTOSCScraping", "group__oscscraping.html", "group__oscscraping" ],
    [ "SDTOSCSpectralFeats", "group__oscspectralfeats.html", "group__oscspectralfeats" ],
    [ "SDTOSCWindCavity", "group__oscwindcavity.html", "group__oscwindcavity" ],
    [ "SDTOSCWindFlow", "group__oscwindflow.html", "group__oscwindflow" ],
    [ "SDTOSCWindKarman", "group__oscwindkarman.html", "group__oscwindkarman" ],
    [ "SDTOSCZeroCrossing", "group__osczerox.html", "group__osczerox" ]
];