var modules =
[
    [ "Friction", "group__friction.html", "group__friction" ],
    [ "Open Sound Control", "group__osc.html", "group__osc" ],
    [ "SDTAnalysis.h: Sound analysis tools", "group__analysis.html", "group__analysis" ],
    [ "SDTCommon.h: Common variables and functions", "group__common.html", "group__common" ],
    [ "SDTCommonMacros.h: Macros", "group__commonmacros.html", "group__commonmacros" ],
    [ "SDTComplex.h: Handling complex numbers", "group__complex.html", "group__complex" ],
    [ "SDTControl.h: Compound solid interactions", "group__control.html", "group__control" ],
    [ "SDTDCMotor.h: Electric motors", "group__dcmotor.html", "group__dcmotor" ],
    [ "SDTDemix.h: Transient/tonal/residual components separator", "group__demix.html", "group__demix" ],
    [ "SDTEffects.h: Digital audio effects", "group__effects.html", "group__effects" ],
    [ "SDTFFT.h: Fast Fourier Transform", "group__fft.html", "group__fft" ],
    [ "SDTFilters.h: Audio filters", "group__filters.html", "group__filters" ],
    [ "SDTGases.h: Air turbulence and explosions", "group__gases.html", "group__gases" ],
    [ "SDTInteractors.h: interactions between solids", "group__interactors.html", "group__interactors" ],
    [ "SDTJSON.h: JSON", "group___j_s_o_n.html", "group___j_s_o_n" ],
    [ "SDTLiquids.h: Liquid sounds", "group__liquids.html", "group__liquids" ],
    [ "SDTMotor.h: Combustion engines", "group__motor.html", "group__motor" ],
    [ "SDTOSC.h: Open Sound Control", "group__osc__h.html", "group__osc__h" ],
    [ "SDTOSCAnalysis.h: OSC for sound analysis tools", "group__oscanalysis.html", "group__oscanalysis" ],
    [ "SDTOSCControl.h: OSC for compound solid interactions", "group__osccontrol.html", "group__osccontrol" ],
    [ "SDTOSCDCMotor.h: OSC DCMotor", "group___o_s_c_d_c_motor.html", "group___o_s_c_d_c_motor" ],
    [ "SDTOSCDemix.h: OSC Demix", "group___o_s_c_demix.html", "group___o_s_c_demix" ],
    [ "SDTOSCEffects.h: OSC for digital audio effects", "group__osceffects.html", "group__osceffects" ],
    [ "SDTOSCFilters.h: OSC for audio filters", "group__oscfilters.html", "group__oscfilters" ],
    [ "SDTOSCGases.h: OSC for air turbulence and explosions", "group__oscgases.html", "group__oscgases" ],
    [ "SDTOSCInteractors.h: OSC Interactors", "group___o_s_c_interactors.html", "group___o_s_c_interactors" ],
    [ "SDTOSCLiquids.h: OSC for liquid sounds", "group__oscliquids.html", "group__oscliquids" ],
    [ "SDTOSCMotor.h: OSC Motor", "group___o_s_c_motor.html", "group___o_s_c_motor" ],
    [ "SDTOSCProjects.h: OSC Projects", "group__osc__projects.html", "group__osc__projects" ],
    [ "SDTOSCResonators.h: OSC Resonators", "group___o_s_c_resonators.html", "group___o_s_c_resonators" ],
    [ "SDTOscillators.h: Oscillators", "group__oscillators.html", "group__oscillators" ],
    [ "SDTProjects.h: SDT Projects", "group__sdt__projects.html", "group__sdt__projects" ],
    [ "SDTResonators.h: Solid resonators", "group__resonators.html", "group__resonators" ],
    [ "SDTStructs.h: Common data structures", "group__structs.html", "group__structs" ]
];